# Generated by Django 3.0.5 on 2020-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opentime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', models.DateField(verbose_name='Available Day')),
                ('available_from', models.TimeField(verbose_name='Available from')),
                ('available_until', models.TimeField(verbose_name='Available Until')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
